export const loaderMessages = [
  "Processing your Skyjo grid… Please wait.",
  "Analyzing your photo… Hang tight for your results!",
  "Calculating the points, just a moment!",
  "Scanning your Skyjo grid… Almost there!",
  "Looking at your cards… Just a moment!",
  "Magic in progress! Calculating your points now… ✨",
  "Analyzing your board… This won’t take long!",
  "Crunching the numbers… Who’s winning this round?",
  "Let’s see how your hand stacks up… Hang tight!",
  "Shuffling through your cards… Almost done!",
  "Your Skyjo grid is under review… Stay tuned!",
  "Checking your cards for the best strategy…",
  "Finalizing the scores… One sec!",
  "Did you know? The lower your points, the better!",
  "Tip: Watch out for those high cards. They can cost you big!",
  "Don’t forget—calculations are done automatically, so you can focus on strategy!",
  "Skyjo Pro Tip: Swapping cards at the right time can save you points!",
  "Did you know? Negative cards are your best friends!",
  "The key to winning? Keep your total as low as possible!",
  "A single high-value card can ruin your round… Play wisely!",
  "Planning ahead is the secret to Skyjo mastery!",
  "Don’t just reveal—swap strategically!",
  "Small changes can make a big difference… Think before you swap!",
  "Skyjo is all about patience and timing!",
  "Smart moves now = fewer points later!",
  "Every round is a fresh start… Adapt your strategy!",
];
